# Generated by Django 4.0.6 on 2022-07-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumnail_image_url',
            new_name='thumbnail_image_url',
        ),
    ]
