# Generated by Django 4.0.6 on 2022-07-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_thumnail_image_url_product_thumbnail_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cololr',
            new_name='color',
        ),
    ]
